### ISSUE TITLE
Imprint page footer has duplicate link to "imprint"

### ISSUE THREAD

**Issue by gautamdhameja** [bigchaindb/site#183]
https://www.bigchaindb.com/imprint/

<img width="374" alt="screen shot 2017-10-20 at 17 42 14" src="https://user-images.githubusercontent.com/5374052/31829722-6c3b9740-b5be-11e7-8685-cecd8d94a5b6.png">

**Comment by kremalicious** [comment]
@gautamdhameja could you check if this is still happening for you please? Lots of changes have been deployed since you reported it and if we're lucky issue just went away.

**Comment by gautamdhameja** [comment]
Just checked on `Chrome + Windows` and not able to reproduce the issue anymore.

**Comment by kremalicious** [comment]
great, thanks! I like issues which solve itself
