### ISSUE TITLE
All tutorials should be in Github

### ISSUE THREAD

**Issue by arsen3d** [bigchaindb/site#247]
This tutorial can be cleaned up.
* newUser is specified but never used
<img width="787" alt="screenshot 2018-05-31 10 43 08" src="https://user-images.githubusercontent.com/298235/40808588-8018d9e4-64dc-11e8-9e88-7f5ae778de24.png">

**Comment by kremalicious** [comment]
@arsen3d could you specify what exactly you mean with "All tutorials should be in Github"? What other tutorials are you referring to?
