### ISSUE TITLE
Convert multi language code block examples into tabs

### ISSUE THREAD

**Issue by innoprenuer** [bigchaindb/site#254]
Our current tutorials are javascript heavy and it gives the wrong impression that bigchaindb have better support for javascript and less support for python and java (which is not true as we are officially supporting all 3 drivers).

So there is a need to support multi tab code snippets for our existing tutorials and guides.

> Before 

![image](https://user-images.githubusercontent.com/7534044/43899552-a0e543aa-9be2-11e8-8a4e-7acc51b41379.png)

> After (incl Java)

![image](https://user-images.githubusercontent.com/7534044/43899535-90c5f5c8-9be2-11e8-849b-dc0e1194c2bd.png)

**Comment by kremalicious** [comment]
this would be the perfect implementation, consecutive fenced code blocks getting transformed into tabs: https://yacir.github.io/markdown-fenced-code-tabs/

Anyone wants to port that to ruby? 🙃

But to solve the initial problem, an interim solution would be to first write out the code examples beneath each other. Then figure out later how to make tabs out of them. Would only require to add the language as a visible label to code blocks.
