### ISSUE TITLE
Remove consulting section and request submission form from BDB website

### ISSUE THREAD

**Issue by chalidbdb** [bigchaindb/site#275]
Request on BDB website will not be handled by BigchainDB GmbH. The issue should remove the consulting service section and request functionality:
- https://www.bigchaindb.com/services/
- https://www.bigchaindb.com/services/#contact

**Comment by ttmc** [comment]
Matthias wrote, "...there’s a lot attached in the background, formspree, zapier, Google Sheets which all needs to be changed and/or shutdown."
